# Generated by Django 5.0.1 on 2024-01-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_model_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPUVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_vendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboardModel_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboardVendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPU_name', models.CharField(default='', max_length=255)),
                ('CPU_frequency', models.FloatField()),
                ('CPUModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.cpumodel')),
            ],
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='CPUVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.cpuvendor'),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.CharField(default='', max_length=255)),
                ('motherboardModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.motherboardmodel')),
            ],
        ),
        migrations.AddField(
            model_name='motherboardmodel',
            name='motherboardVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.motherboardvendor'),
        ),
    ]
