# Generated by Django 5.0.1 on 2024-02-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_model_name', models.CharField(default='', max_length=255)),
                ('storage_model_memory', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StorageVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_vendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(default='', max_length=255)),
                ('storage_serial', models.CharField(default='', max_length=255)),
                ('storageModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.storagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='storageType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.storagetype'),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='storageVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.storagevendor'),
        ),
    ]
