# Generated by Django 5.0.1 on 2024-02-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_storagemodel_storagetype_storagevendor_storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideocardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videocard_model_name', models.CharField(default='', max_length=255)),
                ('videocard_model_memory', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideocardVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videocard_vendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videocard_name', models.CharField(default='', max_length=255)),
                ('videocardModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.videocardmodel')),
            ],
        ),
        migrations.AddField(
            model_name='videocardmodel',
            name='videocardVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.videocardvendor'),
        ),
    ]
