# Generated by Django 5.0.1 on 2024-02-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_videocardmodel_videocardvendor_videocard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_inventory_number', models.CharField(default='', max_length=255)),
                ('computer_name', models.CharField(default='', max_length=255)),
                ('computer_arch', models.CharField(default='', max_length=255)),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.cpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.motherboard')),
            ],
        ),
    ]
