# Generated by Django 5.0.1 on 2024-02-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(default='', max_length=255)),
                ('audience_state', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.audience'),
        ),
    ]
