# Generated by Django 5.0.1 on 2024-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_audience_computer_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='audience_state',
            field=models.JSONField(null=True),
        ),
    ]
