# Generated by Django 5.0.1 on 2024-02-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_audience_audience_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_model_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RAMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_type_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RAMVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_vendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(default='', max_length=255, null=True)),
                ('ram_memory', models.FloatField()),
                ('ram_frequency', models.FloatField()),
                ('ramModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.rammodel')),
            ],
        ),
        migrations.AddField(
            model_name='rammodel',
            name='ramType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.ramtype'),
        ),
        migrations.AddField(
            model_name='rammodel',
            name='ramVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.ramvendor'),
        ),
    ]
