# Generated by Django 5.0.1 on 2024-02-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rammodel_ramtype_ramvendor_ram_rammodel_ramtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_vendor_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_model_name', models.CharField(default='', max_length=255)),
                ('monitorVendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.monitorvendor')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_inventory_number', models.CharField(default='', max_length=255)),
                ('monitor_name', models.CharField(default='', max_length=255)),
                ('monitor_serial_number', models.CharField(default='', max_length=255)),
                ('monitor_resolution', models.CharField(default='', max_length=255)),
                ('monitor_resolution_format', models.CharField(default='', max_length=255, null=True)),
                ('monitorModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.monitormodel')),
                ('monitorVendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.monitorvendor')),
            ],
        ),
    ]
