# Generated by Django 5.0.1 on 2024-02-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_monitorvendor_monitormodel_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='monitorVendor',
        ),
    ]
