# Generated by Django 5.0.1 on 2024-02-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_monitor_monitorvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
        migrations.AddField(
            model_name='ram',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
        migrations.AddField(
            model_name='storage',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
    ]
