# Generated by Django 5.0.1 on 2024-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_monitor_computer_ram_computer_storage_computer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocardmodel',
            name='videocardVendor',
        ),
        migrations.AddField(
            model_name='videocardmodel',
            name='videocardVendors',
            field=models.ManyToManyField(blank=True, related_name='videocardVendors', to='home.videocardvendor'),
        ),
    ]
