# Generated by Django 5.0.1 on 2024-02-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_videocardmodel_videocardvendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='motherboard',
        ),
        migrations.AddField(
            model_name='cpu',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.computer'),
        ),
    ]
